### ISSUE TITLE
Glamorous doesn't work with React v16

### ISSUE THREAD

**Issue by rafaelklaessen** [paypal/glamorous#358] opened 2017-11-21 09:27 UTC
- `glamorous` version: 4.11.0
- `glamor` version: 2.20.40
- `react` version: 16.1.1

Problem description:
I'm trying to use glamorous with React v16. This throws an error:
`Uncaught TypeError: Cannot read property 'object' of undefined`
Which is because Glamorous accesses PropTypes via the React package.
(As confirmed by the warning when using React v15.6.2: `Warning: Accessing PropTypes via the main React package is deprecated, and will be removed in  React v16.0.`)

Suggested solution:
Use the prop-types package instead.

**Comment by Ailrun** [comment] 2017-11-21 15:32
@rafaelklaessen Thank you for reporting this!
@kentcdodds Could you check this...?

**Comment by kentcdodds** [comment] 2017-11-21 15:40
It is supported. Please see https://help.glamorous.rocks

**Comment by Ailrun** [comment] 2017-11-21 15:47
@kentcdodds 
https://github.com/paypal/glamorous/blob/0076e2676568911f0027c8f70634dfc17d697470/src/react-compat.js#L94
We use `React.PropTypes` if it's not a Preact.
(Since we use `import PropTypes from './react-compat';` somewhere...)

**Comment by kentcdodds** [comment] 2017-11-21 16:20
The way it works is a little complicated, but I assure you that if you're using a react version 15.5 or greater that we attempt to require `prop-types` if it's available, otherwise we'll use `React.PropTypes`. If you see https://help.glamorous.rocks/ you'll notice there's no console warning _and_ we're using React@16

The problem is with @rafaelklaessen's implementation.

I'm not sure how long we'll support `React.PropTypes`, but it's not time to drop support now.

**Comment by Ailrun** [comment] 2017-11-21 16:22
@kentcdodds Oh, I miss that `else` part. Thank you for correcting me.

**Comment by kentcdodds** [comment] 2017-11-21 16:40
I'm going to go ahead and close this because I'm 99% certain that we wont be needing to make any changes in glamorous. Feel free to keep the conversation going if you need help.

**Closed by kentcdodds** 2017-11-21 16:40 UTC

**Comment by rafaelklaessen** [comment] 2017-11-21 17:40
Thank you! I forgot that I didn't have prop-types installed at the time.

(Maybe you could throw a custom error in this case because the current error might be unclear?)

**Comment by kentcdodds** [comment] 2017-11-21 17:59
It's alright. I think it's really not all that harmful with the way things are now so I don't think we'll make any changes. We'll eventually drop support for React.PropTypes anyway and require you install `prop-types`.

**Comment by ajwhite** [comment] 2017-11-21 18:44
As a side note, there is a helpful note when running `npm install` when `peerDependencies` are unsatisfied
