### ISSUE TITLE
add an api for "pure" styles to explicitly be declared.

### ISSUE THREAD

**Issue by tkh44** [paypal/glamorous#203] opened 2017-06-30 18:20 UTC
Problem description:

You want to flag to glamorous to only calculate the className once.

If a dev's styles have **no dynamic values** then why calculate on every render?

Suggested solution:

Add this api

```javascript
glamorous.pure.div({ color: 'blue' })

// or

glamorous.div.pure({ color: 'blue' })

// or

glamorous(
  'div',
  {pure: true}
)
```

I think you can convert normal calls to glamorous to "pure" calls with the existing plugin if this is added.

**Comment by kentcdodds** [comment] 2017-06-30 18:30
This is awesome! Yes, I definitely want this. How would this work with the `css` prop? Would we do something with `componentWillReceiveProps` to check whether it's changed and only recalculate if that prop had any changes?

**Comment by tkh44** [comment] 2017-06-30 18:33
If it is marked as pure then the css prop should be pure as well, right?

**Comment by kirkstrobeck** [comment] 2017-06-30 18:35
Another API option?

```js
<Div
  css={{
    glamorousPure: true,
  }}
>🚀</Div>
```

Future config options could have that format too.

**Comment by kentcdodds** [comment] 2017-06-30 18:36
> If it is marked as pure then the css prop should be pure as well, right?

That makes sense. Hard though when you may be passing this component around to be reusable. But maybe you'd just not make the reusable ones pure 🤔 

> Another API option?

That's interesting... I'm going to push back on that a bit. It would add a bit of complexity to things and I want to be sure it's worth it before we go for it.

**Comment by kirkstrobeck** [comment] 2017-06-30 18:50
```js
<Div
  pure={true}
  css={{ background: 'red' }}
>🚀</Div>
```

**Comment by kentcdodds** [comment] 2017-06-30 18:56
I like that better :+1:

But could we discuss that one in another issue? I'd like to discuss it separate from this.

Thanks!

**Comment by kentcdodds** [comment] 2017-07-10 15:07
Anyone wanna work on this? Would be great to add this to the list of announcements when we do the big release in a week or two!

**Comment by fgnass** [comment] 2017-07-11 07:59
What about a simpler solution: Opt out of the pure rendering whenever `css` or `className` is used. In all other cases consider the component to be pure if only style objects (no functions) are passed to the factory. Would this work?

**Comment by kentcdodds** [comment] 2017-07-11 16:44
Thanks for the input @fgnass, the problem is that you don't at the time of creating your component class whether it really should be pure or not because `css` and `className` are provided at render-time, not definition time. So what this would do is effectively disallow those props from affecting the className provided.

**Comment by tkh44** [comment] 2017-07-11 17:39
@kentcdodds I've been thinking about this. I'm starting to wonder if a special lifecycle hook would be better. You touched on it ☝️

```
glamorous(
  'div',
  {
    shouldClassNameUpdate: (props, prevProps) => {
       // return false for pure
       return props.foo !== prevProps.foo
    }
  }
)
```

**Comment by kentcdodds** [comment] 2017-07-11 17:54
Ok, yeah, that seems like it'd be a nice primitive upon which other handy things could be built. I like that the most. Could call it [here](https://github.com/paypal/glamorous/blob/3eb276a7dd7b3d2e6192214578c6f73e9994918a/src/create-glamorous.js#L60-L71) and skip all that class name construction. Would be great for perf. Then we could later add a `.pure` which implements that to always return false :smile:

**Comment by kentcdodds** [comment] 2017-07-26 04:36
I'm going to implement this really quick. Standby...

**Comment by kentcdodds** [comment] 2017-07-26 04:43
What role should `context` play in this? 🤔 

The API for dynamic styles is `(props, context) => {}` so shouldn't that map well to `shouldClassNameUpdate`? Maybe: `(nextProps, props, nextContext, context) => {}`?

**Comment by kentcdodds** [comment] 2017-07-26 05:21
If the `css` prop changes, then we probably want to update the classname. Should we skip calling `shouldClassNameUpdate` and just update the class name in that case? Seems like we should.

**Comment by kentcdodds** [comment] 2017-07-26 05:51
Actually, scratch that, I don't want to deal with doing a deep equality check of `css` prop... We'll let end users do that...

**Comment by tkh44** [comment] 2017-07-26 05:59
Maybe look at https://github.com/acdlite/recompose/blob/master/docs/API.md#withpropsonchange. Might be some inspiration there.

**Comment by kentcdodds** [comment] 2017-07-26 06:04
Thanks @tkh44. I think I've got it. Care to take a look? https://github.com/paypal/glamorous/pull/250

**Comment by kentcdodds** [comment] 2017-07-27 05:26
This will be released when `next` is released.

**Closed by kentcdodds** 2017-07-27 05:26 UTC
Labels: enhancement, help wanted
