### ISSUE TITLE
Memory Leak caused by typings

### ISSUE THREAD

**Issue by kaoDev** [paypal/glamorous#288] opened 2017-08-16 09:54 UTC
- `glamorous` version: 4.1.2
- `glamor` version: 2.20.40
- `react` version: 16

Relevant code.

```javascript

```

What you did:
I used glamorous with typescript and the more components I added to the project the slower it got until I reached the `FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory`

What happened:
the typescript compiler got stuck in a loop

Reproduction:
unfortunately the reproduction is not trivial, but I think any larger project using typescript and glamorous will run into this

-- paste your link here --

Problem description:
The CSSProperties and SVGProperties types both are declared with the helper type 
```typescript
export type SingleOrArray<Properties, T extends keyof Properties> = {
  [P in T]: Properties[P] | Array<Properties[P]>
}
```
from https://github.com/paypal/glamorous/blob/master/typings/helpers.d.ts
this causes some kind of infinite loop eating up huge amounts of memory.

Suggested solution:
For me the fix was to remove this helper, but it was just merged with https://github.com/paypal/glamorous/pull/260 so perhaps @luke-john can say a bit more

**Comment by luke-john** [comment] 2017-08-16 11:40
Hey @kaoDev, thanks for the bug report and investigation.

We also had oom errors with upgrading to v4 in our component library at work due to a seperate issue with the usage of typescript `extends`.  It seems `extends` are not great with memory at the moment :(.

This `extends` could be replaced by additional interfaces for css and svg properties which does this the long way round, ie.

```ts
export interface CSSPropertiesCompleteArray {
    alignContent?: Array<CSSPropertiesCompleteSingle['alignContent']>
    // ...
}
```

I'm unlikely to get time to open a pr to do this in the coming days, but may get this done over the weekend.  If someone else is able to do this in the meantime (or can think of an alternate solution) that would be great.

**Comment by kaoDev** [comment] 2017-08-16 12:21
I just realised that there is something else causing the oom problem. When I filed the issue and had a working build I had parts of the v3.25.0 typings in use. Just removing the `SingleOrArray` helper is not enough.

So the real workaround for typescript right now is use v3.25.0

**Comment by luke-john** [comment] 2017-08-16 13:03
Just had another quick look.

Running the following in the glamorous repo shows a ~80mb difference (less memory usage) when compiling the tests with the component factory overloads working as intended.

`node ./node_modules/.bin/tsc --diagnostics --noEmit`

https://github.com/luke-john/glamorous/pull/2

**Comment by luke-john** [comment] 2017-08-16 13:06
The Omit and usage of extends was inspired by styled-components, but originated from https://github.com/Microsoft/TypeScript/issues/12215.

Based on that discussion though it looks like there's lot's of people doing similar things so I'm hesitant to blame the out of memory on that without a very clear scaled down reproduction.

**Comment by luke-john** [comment] 2017-08-18 12:18
I've just opened a PR which should significantly cut down the memory usage.  Thanks again for reporting this.

https://github.com/paypal/glamorous/pull/291

**Comment by kaoDev** [comment] 2017-08-18 12:36
cool, and thank you for reacting so fast 😃 
I will try the new typings and report back

**Comment by kentcdodds** [comment] 2017-08-18 14:50
Merged!

**Closed by kentcdodds** 2017-08-18 14:50 UTC
Labels: TypeScript

**Comment by kaoDev** [comment] 2017-08-21 09:05
just to confirm, https://github.com/Microsoft/TypeScript/issues/17097 fixed my problems :) thank you @luke-john

**Comment by luke-john** [comment] 2017-08-21 11:44
Great to hear, thanks for reporting it.

**Comment by GeeWee** [comment] 2017-08-30 06:17
This is really great! It reduced our check time in tsc from 15s to <5s - and turned the watch mode bearable, where previously it took 20+s and ran out of memory after a little while. Great work!
