### ISSUE TITLE
glamorous.path does not render the `d` attribute

### ISSUE THREAD

**Issue by eyelidlessness** [paypal/glamorous#97] opened 2017-05-01 19:35 UTC
- `glamorous` version: 3.13.0
- `glamor` version: 2.20.24
- `react` version: 15.5.4

**Relevant code.**

See repro.

**What you did:**

Tried to style a `path` in an SVG.

**What happened:**

The `d` attribute is not rendered.

**Reproduction:**

https://codesandbox.io/s/zmGG3ZlR5

**Problem description:**

`glamorous.path` does not render the `d` attribute.

**Suggested solution:**

`glamorous.path` should render the `d` attribute.

**Comment by kentcdodds** [comment] 2017-05-01 19:37
Thanks for the complete report @eyelidlessness! I'm going to say this is a duplicate of #91 which should hopefully be solved relatively soon with https://github.com/paypal/glamorous/pull/93 feel free to chime in there with feedback and help us come to a good solution :)

**Closed by kentcdodds** 2017-05-01 19:37 UTC

**Comment by eyelidlessness** [comment] 2017-05-01 19:40
Thanks for the super quick response!

**Comment by kentcdodds** [comment] 2017-05-01 19:41
Sure thing! I just happened to be looking :)
